---
title: "Benchmarking {SpeedyMarkov}"
author: "Sam Abbott"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmarking {SpeedyMarkov}}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>",
  fig.width = 7, fig.height = 7, 
  fig.align = "center"
)
```

## Define benchmarking function


```{r}
library(SpeedyMarkov)
library(ggplot2)
library(microbenchmark)
library(parallel)
library(furrr)

# Set up grid to be used across models
# Not in Rstudio future currently defaults to multisession rather than multicore which may be slower. 
benchmark_approaches <- function(model = NULL, reference = NULL, 
                                 duration = NULL, samples = NULL,
                                 times = NULL) {
  ## Start up parallel sessions
  future::plan(future::multiprocess, workers = 4);
  
  benchmark <- microbenchmark::microbenchmark(
  "Reference" = {
    reference(cycles = duration, samples = samples)
    },
  "SpeedyMarkov - R" = {
    markov_ce_pipeline(model(),
                       duration = duration, 
                       samples = samples,
                       sim_type = "base")
    },
    "SpeedyMarkov - Rcpp inner loop" = {
    markov_ce_pipeline(model(),
                       duration = duration, 
                       samples = samples,
                       sim_type = "armadillo_inner")
    },
    "SpeedyMarkov - Rcpp simulation" = {
    markov_ce_pipeline(model(),
                       duration = duration, 
                       samples = samples,
                       sim_type = "armadillo_all")
    },
    "SpeedyMarkov - Rcpp simulation - lapply" = {
    markov_ce_pipeline(model(),
                       duration = duration, 
                       samples = samples,
                       sim_type = "armadillo_all",
                       map_fn = lapply)
    },
   "SpeedyMarkov - Rcpp simulation - mclapply (2 cores)" = {
    markov_ce_pipeline(model(),
                       duration = duration, 
                       samples = samples,
                       sim_type = "armadillo_all",
                       map_fn = parallel::mclapply,
                       mc.cores = 2)
    },
     "SpeedyMarkov - Rcpp simulation - mclapply (4 cores)" = {
    markov_ce_pipeline(model(),
                       duration = duration, 
                       samples = samples,
                       sim_type = "armadillo_all",
                       map_fn = parallel::mclapply,
                       )
    },
       "SpeedyMarkov - Rcpp simulation - furrr::future_map (4 cores)" = {
    markov_ce_pipeline(model(),
                       duration = duration, 
                       samples = samples,
                       sim_type = "armadillo_all",
                       map_fn = furrr::future_map)
    },
  times = times)
  
  return(benchmark)
}
```

## Two state Markov model

Run the benchmarks for the two state model for 100 cycles, across 100,000 samples, 10 times for each test.

```{r}
## Specifiy the number of samples and duration over which to model
## Specfiy the reference and SpeedyMarkov model
results <- benchmark_approaches(model = example_two_state_markov, 
                                reference = reference_two_state_markov,
                                duration = 100, samples = 100000,
                                times = 10) 

results
```

Plot benchmark results

```{r, width = 10, height = 10}
ggplot2::autoplot(results) +
  ggplot2::theme_minimal()
```

