---
title: "Profiling the reference implementations"
author: "Sam Abbott"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started with {SpeedyMarkov}}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>",
  fig.width = 7, fig.height = 7, 
  fig.align = "center"
)
```


## Background



## Profiling

Again profiling indicates that the interior iteratively updated for loop operation accounts for the vast majority of the function run time. 

Strategies suggested for the reference application also hold here.


### R implementation

```{r}
library(SpeedyMarkov)
library(profvis)

profvis({
  markov_ce_pipeline(example_two_state_markov(), duration = 100, samples = 10000,
                     sim_type = "base")
})
```

### R  implementation augmented with Rcpp 

```{r}
library(SpeedyMarkov)
library(profvis)

profvis({
  markov_ce_pipeline(example_two_state_markov(), duration = 100, samples = 10000,
                     sim_type = "armadillo_inner")
})
```

### R implementation further augmented with Rcpp

```{r}
library(SpeedyMarkov)
library(profvis)

profvis({
  markov_ce_pipeline(example_two_state_markov(), duration = 100, samples = 10000,
                     sim_type = "armadillo_all")
})
```

## Benchmark

