// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ArmaMarkovLoop
SEXP ArmaMarkovLoop(arma::mat sim, arma::rowvec cohort, arma::mat transition, int duration);
RcppExport SEXP _SpeedyMarkov_ArmaMarkovLoop(SEXP simSEXP, SEXP cohortSEXP, SEXP transitionSEXP, SEXP durationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type sim(simSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type cohort(cohortSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type transition(transitionSEXP);
    Rcpp::traits::input_parameter< int >::type duration(durationSEXP);
    rcpp_result_gen = Rcpp::wrap(ArmaMarkovLoop(sim, cohort, transition, duration));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpeedyMarkov_ArmaMarkovLoop", (DL_FUNC) &_SpeedyMarkov_ArmaMarkovLoop, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpeedyMarkov(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
