# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title An inner Markov loop implemented using RcppArmadillo
#' @inherit markov_loop
#' @export
#' @useDynLib SpeedyMarkov, .registration=TRUE
#' @examples
#' 
#' transition <- matrix(rnorm(4), 2, 2)
#' sim <- matrix(NA, 100, 2)
#' cohort <- c(1, 0)
#' duration <- 100
#' 
#' # Reference R implementation
#' sim_r <- markov_loop(sim, cohort, transition, duration)
#' 
#' # RcppArmadillo implementation
#' sim_rcppArma <- ArmaMarkovLoop(sim, cohort, transition, duration)
#' 
#' # Check results are within tolerances
#' all.equal(sim_r, sim_rcppArma)
#' 
#' # Benchmark
#' library(microbenchmark)
#' microbenchmark(markov_loop(sim, cohort, transition, duration), 
#'                ArmaMarkovLoop(sim, cohort, transition, duration), 
#'                times = 1000)
ArmaMarkovLoop <- function(sim, cohort, transition, duration) {
    .Call(`_SpeedyMarkov_ArmaMarkovLoop`, sim, cohort, transition, duration)
}

